version: '3'

services:
    pgadmin:
      image: dpage/pgadmin4
      restart: unless-stopped
      volumes:
        - ./data:/var/lib/pgadmin
      environment:
        - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
        - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pgadmin.rule=Host(`$HOSTNAME`)"
        - "traefik.http.routers.pgadmin.entrypoints=websecure"
        - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      networks:
        - proxy

networks:
  proxy:
    external: true
